Fix tail
sdc50/ubi-tethys-docker pull request #5
Opened 2024-07-11 22:52 UTC by gronka

Change the long-lived process from supervisord to tail, and prepend tail lines with the name of the file. Also, tail our Daphne logs

2024-07-17 16:31 UTC, araglu commented
I tried using "awk" to avoid spawning so many tail processes, but this implementation is difficult to read. "tail" also complains about "inotify cannot be used, reverting to polling" here; I never saw that error when using tail_file(). I think I prefer tail_file() because it is easier to read.

```shell
tail_logs=""
for log_file in "${log_files[@]}"; do
  tail_logs="${tail_logs} ${log_file}"
done
for i in $(seq -f "%02g" 1 $NUM_PROCESSES); do
  tail_logs="${tail_logs} tethys/tethys${i}.log"
done
cd /var/log/
# The awk command prepends each line with the filename.
#    stdbuf -o0    - Disable buffering from pipe.
#    /^==>[^<]*<==$/    - Look for the filename. When tail displays output from a different file, it prints a newline and "==> httpd/access_log <==".
#    {a=substr($0, 5, length-8); next}    - Grab the whole line ($0), chop off the arrows to grab only the filename (supports spaces), store in variable "a", and don't print this line (next).
#    ! /^$/    - Ignore blank lines. "tail" prints one blank line before switching to a different file.
#    {printf ..., a, $0}    - Print the filename (a) and then the whole line ($0).
#    "\033[35m%-27s:\033[0m%s\n"    - Print in purple (\033[35m), print the filename left-aligned with 27 spaces (%-27s), print a colon, reset colors (\033[0m), print line from log (%s), print newline (\n).
tail -F -n 0 ${tail_logs} | stdbuf -o0 awk '/^==>[^<]*<==$/ {a=substr($0, 5, length-8); next} ! /^$/ {printf "\033[35m%-27s:\033[0m%s\n", a, $0}'
```

Based on https://superuser.com/a/1123674, https://stackoverflow.com/a/76020371, https://unix.stackexchange.com/a/195930, and the [gawk manual](https://www.gnu.org/software/gawk/manual/html_node/index.html).

2024-07-18 14:58 UTC, araglu requested changes

2024-07-18 14:58 UTC, araglu commented on docker/run.sh
> +  tail -qF $file | sed "s|^|$1${PAD}:|g" &
```suggestion
  ALIGN=27
  PREFIX=$(printf "%-${ALIGN}s:" "$1")
  file="/var/log/$1"
  # each tail runs in the background but prints to stdout
  # sed outputs each line from tail prepended with the filename+padding
  tail -qF $file | sed --unbuffered "s|^|$PREFIX|g" &
```

This adds "--unbuffered" to sed because "docker logs" was not showing updates until several new lines appeared in the file. Now it streams updated lines immediately.

I also converted it to printf for simplicity and to avoid a call to perl.

2024-07-18 20:38 UTC, gronka commented
I adopted the use of `sed --unbuffered` and the variable name `PREFIX`. The way you set the `PREFIX` variable is neat, but it's a bit obscure for non-bash programmers, imo.

2024-11-05 20:31 UTC, merged